# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "de"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  # - MediumFollowersCountPlugin:
  #    username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - juekr/awesome-podcasting-german
      - juekr/remote-friendship-lamp

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Jürgen Krauß – #Painfluencer, Writer, Podcaster"

# Avatar image path
avatar: "https://brandad.de/templates/yootheme/cache/ea/juergenkrauss_2400_1350px-ea3c4e0b.webp" 
# "./images/profile.jpeg"

# Name section text
name: "@esisteinkrauss"

# Tagline section text
tagline: >-
    Guy from Germany. Good with words. Good with podcasts. 
    Not so good with chronic pain.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fas fa-link"
      text: "Webseite: es-ist-ein-krauss.de"
      url: "https://es-ist-ein-krauss.de"
      alt: "Webseite: es-ist-ein-krauss.de"
      title: "Webseite: es-ist-ein-krauss.de"
      target: "_blank"
  - link:
      icon: "fa-solid fa-rss"
      text: "Podcast: Schmerzenssache"
      url: "https://schmerz.fm"
      alt: "Podcast: Schmerzenssache"
      title: "Podcast: Schmerzenssache"
      target: "_blank"
  - link:
      icon: "fa-solid fa-rss"
      text: "Podcast: Ach? Triumvirat für historisch inspirierte Humorvermittlung"
      url: "https://das-a.ch"
      alt: "Podcast: Ach? Triumvirat für historisch inspirierte Humorvermittlung"
      title: "Podcast: Ach? Triumvirat für historisch inspirierte Humorvermittlung"
      target: "_blank"
  - link:
      icon: "fas fa-link"
      text: "Geschichtspodcasts.de"
      url: "https://geschichtspodcasts.de"
      alt: "Geschichtspodcasts"
      title: "Geschichtspodcasts"
      target: "_blank"
  - link:
      icon: "fas fa-link"
      text: "Podcast-Event-Serie in Nürnberg: Podcast-Brause"
      url: "https://podcast-brause.de"
      alt: "Die wahrscheinlich einzige, sicher aber prickelndste Podcast-Live-Eventreihe in Nürnberg! 🥂"
      title: "Die wahrscheinlich einzige, sicher aber prickelndste Podcast-Live-Eventreihe in Nürnberg! 🥂"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/juekr"
      title: "juekr GitHub"
      alt: "juekr GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/esisteinkrauss/"
      title: "Jürgens LinkedIn"
      alt: "Jürgens LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/esisteinkrauss/"
      title: "@esisteinkrauss Instagram"
      alt: "@esisteinkrauss Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/schmerzenssache/"
      title: "@schmerzenssache Instagram"
      alt: "@schmerzenssache Instagram"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:juergen@es-ist-ein-krauss.de"
      title: "Email: juergen@es-ist-ein-krauss.de"
      alt: "juergen@es-ist-ein-krauss.de"
      target: "_blank"

# Footer text
footer: >
    Hi there! Follow me on Medium or GitHub, or stay connected on Instagram or LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
# © 2024  <a href="https://link.zhgchg.li" target="_blank">ZhgChgLi</a>. 
copyright: >
  powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
